### ISSUE TITLE
SMTP Error - Unrecognized authentication type

### ISSUE THREAD

**Issue by kmpm** [helpyio/helpy#1219]
Hi, 
I'm trying to set up so that helpy sends email using an office365 account but it keeps failing.

E, [2019-04-01T09:35:23.407739 #25724] ERROR -- : Sucker Punch job error for class: 'ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper' args: [{"job_class"=>"ActionMailer::DeliveryJob", "job_id"=>"e975d454-0484-4fdd-8934-714028e50eb7", "queue_name"=>"mailers", "arguments"=>["TestMailer", "new_test", "deliver_now", "anonymous@changed-it-for-github.test"], "locale"=>:en}]Net::SMTPAuthenticationError 504 5.7.4 Unrecognized authentication type [HE1PR05CA0255.eurprd05.prod.outlook.com]

I obviously obfuscated the email address.
- smtp server: smtp.office365.com
- smtp port: 587

**Comment by kmpm** [comment]
Som more from the log
Looks like it tries to do plain auth but I'm not sure.
```
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/smtp.rb:981:in `check_auth_response'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/smtp.rb:736:in `auth_plain'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/smtp.rb:728:in `authenticate'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/smtp.rb:565:in `do_start'
/home/deploy/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/actionmailer-4.2.11.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/actionmailer-4.2.11.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/actionmailer-4.2.11.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/actionmailer-4.2.11.1/lib/action_mailer/delivery_job.rb:10:in `perform'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/execution.rb:32:in `block in perform_now'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:342:in `block in simple'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:497:in `block in around'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/logging.rb:43:in `tag_logger'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:342:in `block in simple'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:497:in `block in around'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/execution.rb:31:in `perform_now'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/execution.rb:21:in `execute'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/activejob-4.2.11.1/lib/active_job/queue_adapters/sucker_punch_adapter.rb:35:in `perform'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/sucker_punch-2.1.1/lib/sucker_punch/job.rb:60:in `__run_perform'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/sucker_punch-2.1.1/lib/sucker_punch/job.rb:38:in `block in perform_async'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/deploy/.rvm/gems/ruby-2.4.0@helpy/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by kmpm** [comment]
It works with the following change but a prettier fix is needed.
```
diff --git a/app/controllers/application_controller.rb b/app/controllers/application_controller.rb
index 103669d0..9872a025 100644
--- a/app/controllers/application_controller.rb+++ b/app/controllers/application_controller.rb@@ -149,6 +149,7 @@ class ApplicationController < ActionController::Base
         :user_name            => AppSettings["email.smtp_mail_username"].presence,
         :password             => AppSettings["email.smtp_mail_password"].presence,
         :domain               => AppSettings["email.mail_domain"],
+       :authentication       => :login,
         :enable_starttls_auto => !AppSettings["email.mail_smtp"].in?(["localhost", "127.0.0.1", "::1"])
     }
```
