### ISSUE TITLE
Error while trying to load the gem 'themes_on_rails' and restarts

### ISSUE THREAD

**Issue by sGerli** [helpyio/helpy#1250]
Hi, I'm using a Docker container to host Helpy. Today I tried updating it, so I pulled the new image using `docker-compose pull && docker-compose up -d` as suggested by the docs. But after a while, I noticed it was taking too much to start. So I checked the logs and apparently, it's restarting because of the following error.

```
`/home/helpyuser` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'themes_on_rails'.
Gem Load Error is: HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory
Backtrace for gem load error is:
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:1097:in `<module:RbReadline>'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:17:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:10:in `<module:Readline>'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:8:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor.rb:2:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/base.rb:8:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/group.rb:1:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/railties-4.2.11.1/lib/rails/generators.rb:4:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails/engine.rb:1:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails.rb:2:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/helpy/config/application.rb:8:in `<top (required)>'
/helpy/Rakefile:4:in `require'
/helpy/Rakefile:4:in `<top (required)>'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/helpy-bundle/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/opt/helpy-bundle/bin/rake:23:in `load'
/opt/helpy-bundle/bin/rake:23:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bin/bundle:22:in `<main>'
Bundler Error Backtrace:
/helpy/config/application.rb:8:in `<top (required)>'
/helpy/Rakefile:4:in `require'
/helpy/Rakefile:4:in `<top (required)>'
/opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:1097:in `<module:RbReadline>'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/rbreadline.rb:17:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:10:in `<module:Readline>'
/opt/helpy-bundle/gems/rb-readline-0.5.5/lib/readline.rb:8:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/line_editor.rb:2:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/base.rb:8:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/thor-0.20.3/lib/thor/group.rb:1:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/railties-4.2.11.1/lib/rails/generators.rb:4:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails/engine.rb:1:in `<top (required)>'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/helpy-bundle/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
/opt/helpy-bundle/gems/themes_on_rails-0.4.0/lib/themes_on_rails.rb:2:in `<top (required)>'
/helpy/config/application.rb:8:in `<top (required)>'
/helpy/Rakefile:4:in `require'
/helpy/Rakefile:4:in `<top (required)>'
/opt/helpy-bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
```
Docker version 18.04.0-ce, build 3d479c0
Let me know if you need any more info.

**Comment by sGerli** [comment]
I've tried recreating the container. I also tried completely deleting it alongside all of the non-persistent storage and then running pull and up but I still get the same error.

**Comment by sGerli** [comment]
So I found a way to bring my support site back up, the only way I found is downgrading to 2.3.0, neither 2.4.0 or 2.4.1 worked for me. But this still isn't a permanent solution.

**Comment by scott** [comment]
Hi @sGerli thanks for reporting this issue.  I will take a look and see if I can understand what is going on.
