### ISSUE TITLE
Unable upload files to S3 compatible storage by using signature v4

### ISSUE THREAD

**Issue by mzch** [helpyio/helpy#1320]
Hi,

In 2.5.0, Helpy becomes not to upload pictures or other kind of files to S3 compatible storage, Minio by using signature v4 - if using v2, uploading pic will finish successfully. Please fix this issue.

### a part of nginx.conf
```nginx
        passenger_env_var REMOTE_STORAGE true;
        passenger_env_var S3_KEY ***accesskey***;
        passenger_env_var S3_SECRET ***secret***;
        passenger_env_var S3_ENDPOINT https://objstr.com;
        passenger_env_var S3_BUCKET_NAME helpy;
        passenger_env_var S3_PATH_STYLE true;
```

### LOG
```log
I, [2019-05-29T14:32:14.040800 #1643]  INFO -- : Started PUT "/ja/users" for 203.141.134.112 at 2019-05-29 14:32:14 -0700
I, [2019-05-29T14:32:14.043866 #1643]  INFO -- : Processing by RegistrationsController#update as HTML
I, [2019-05-29T14:32:14.044086 #1643]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"pO3HrePH9CWD9ndF3BaCdO09uuyWKeFJxA9g+Vng32a14gsV5kGE1XowDdS5jAKC0f/VupOIJmLGUybG+X/IGA==", "user"=>{"profile_image"=>#<ActionDispatch::Http::UploadedFile:0x000056036d2ac120 @tempfile=#<Tempfile:/tmp/RackMultipart20190529-1643-1ge8l19.jpg>, @original_filename="Face of Myself.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_image]\"; filename=\"Face of Myself.jpg\"\r\nContent-Type: image/jpeg\r\n">, "name"=>"Koichi MATSUMOTO", "company"=>"Office LetLive", "title"=>"", "time_zone"=>"Osaka", "email"=>"koichi@letlive.com", "home_phone"=>"", "cell_phone"=>"", "work_phone"=>"", "street"=>"", "city"=>"Amagasaki-shi", "state"=>"Hyogo", "zip"=>"660-0063", "current_password"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"変更を保存", "locale"=>"ja"}
D, [2019-05-29T14:32:14.047152 #1643] DEBUG -- :   User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
D, [2019-05-29T14:32:14.059114 #1643] DEBUG -- :   User Load (1.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 1]]
D, [2019-05-29T14:32:14.188504 #1643] DEBUG -- :    (1.1ms)  BEGIN
D, [2019-05-29T14:32:14.271654 #1643] DEBUG -- :   SQL (1.4ms)  UPDATE "users" SET "profile_image" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["profile_image", "Face_of_Myself.jpg"], ["updated_at", "2019-05-29 21:32:14.266879"], ["id", 1]]
D, [2019-05-29T14:32:15.923012 #1643] DEBUG -- :    (1.4ms)  ROLLBACK
I, [2019-05-29T14:32:15.923669 #1643]  INFO -- : Completed 500 Internal Server Error in 1879ms (ActiveRecord: 6.7ms)
F, [2019-05-29T14:32:15.925835 #1643] FATAL -- : 
Excon::Error::Forbidden (Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>uploads/user/profile_image/1/Face_of_Myself.jpg</Key><BucketName>helpy</BucketName><Resource>/helpy/uploads/user/profile_image/1/Face_of_Myself.jpg</Resource><RequestId>15A344CB4898DA02</RequestId><HostId>d33a2ac1-3dae-4bfb-ac48-119e6eaa3340</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Accept-Ranges"             => "bytes"
    "Content-Security-Policy"   => "block-all-mixed-content"
    "Content-Type"              => "application/xml"
    "Date"                      => "Wed, 29 May 2019 21:32:15 GMT"
    "Server"                    => "MinIO/RELEASE.2019-05-23T00-29-34Z"
    "Strict-Transport-Security" => "max-age=15552000; includeSubdomains;"
    "Vary"                      => "Origin"
    "X-Amz-Bucket-Region"       => "us-east-1"
    "X-Amz-Request-Id"          => "15A344CB4898DA02"
    "X-Content-Type-Options"    => "nosniff"
    "X-Minio-Deployment-Id"     => "d33a2ac1-3dae-4bfb-ac48-119e6eaa3340"
    "X-Xss-Protection"          => "1; mode=block"
  }
  :host          => "objstr.com"
  :local_address => "148.163.121.238"
  :local_port    => 43348
  :path          => "/helpy/uploads/user/profile_image/1/Face_of_Myself.jpg"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "192.3.176.179"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
):
  app/controllers/registrations_controller.rb:10:in `update_resource'
  app/controllers/application_controller.rb:195:in `set_time_zone'


I, [2019-05-29T14:32:15.939161 #1643]  INFO -- : Processing by ErrorsController#internal_server_error as HTML
I, [2019-05-29T14:32:15.939322 #1643]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"pO3HrePH9CWD9ndF3BaCdO09uuyWKeFJxA9g+Vng32a14gsV5kGE1XowDdS5jAKC0f/VupOIJmLGUybG+X/IGA==", "user"=>{"profile_image"=>#<ActionDispatch::Http::UploadedFile:0x000056036d2ac120 @tempfile=#<Tempfile:/tmp/RackMultipart20190529-1643-1ge8l19.jpg>, @original_filename="Face of Myself.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"user[profile_image]\"; filename=\"Face of Myself.jpg\"\r\nContent-Type: image/jpeg\r\n">, "name"=>"Koichi MATSUMOTO", "company"=>"Office LetLive", "title"=>"", "time_zone"=>"Osaka", "email"=>"koichi@letlive.com", "home_phone"=>"", "cell_phone"=>"", "work_phone"=>"", "street"=>"", "city"=>"Amagasaki-shi", "state"=>"Hyogo", "zip"=>"660-0063", "current_password"=>"[FILTERED]", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"変更を保存", "locale"=>"ja"}
I, [2019-05-29T14:32:15.951186 #1643]  INFO -- :   Rendered errors/internal_server_error.html.erb within layouts/errors (1.4ms)
I, [2019-05-29T14:32:15.963234 #1643]  INFO -- :   Rendered layouts/_google_analytics.html.erb (0.7ms)
I, [2019-05-29T14:32:15.963360 #1643]  INFO -- :   Rendered app/themes/light/views/layouts/_head.html.erb (10.8ms)
I, [2019-05-29T14:32:15.964635 #1643]  INFO -- : Completed 500 Internal Server Error in 25ms (Views: 23.2ms | ActiveRecord: 0.0ms)
```

**Comment by scott** [comment]
@mzch This is fixed in your PR for #1273 right?

**Comment by mzch** [comment]
Unfortunately, applying my PR, Helpy becomes to fail to upload files by using Signature 4....

**Comment by mzch** [comment]
Well, it seems that this is an issue of Minio. I reported this bug to the dev. ref. [Minio Issue #7718](https://github.com/minio/minio/issues/7718)

**Comment by mzch** [comment]
Sorry, my router had a trouble. This is solved.
