### ISSUE TITLE
Docker compose not working on Arch linux, likely because Python 3.8

### ISSUE THREAD

**Issue by DoTheEvo** [helpyio/helpy#1587]
I just assume python, since I see it mentioned in the error logs
Will spin centos or ubuntu to try, but since I already wrote this shit I will just press submitt

<details><summary>console log</summary>
<p>

    helpy_postgres_1 is up-to-date
    helpy_helpy_1 is up-to-date
    Starting helpy_frontend_1 ... 

    ERROR: for helpy_frontend_1  a bytes-like object is required, not 'str'

    ERROR: for frontend  a bytes-like object is required, not 'str'
    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
        response.raise_for_status()
      File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/3680e5e32b0f8a84622c0c85430bd945576b8418e94d54bafaacb164cb8b8ecf/start

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 625, in start_container
        container.start()
      File "/usr/lib/python3.8/site-packages/compose/container.py", line 241, in start
        return self.client.start(self.id, **options)
      File "/usr/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
        return f(self, resource_id, *args, **kwargs)
      File "/usr/lib/python3.8/site-packages/docker/api/container.py", line 1095, in start
        self._raise_for_status(res)
      File "/usr/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/usr/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint helpy_frontend_1 (b4c14cd2959f1a6988f83ae03f17699001a5eec55b320a65f8711a8ed48270f6): Bind for 0.0.0.0:443 failed: port is already allocated'")

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/bin/docker-compose", line 11, in <module>
        load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
      File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 72, in main
        command()
      File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 128, in perform_command
        handler(command, command_options)
      File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1107, in up
        to_attach = up(False)
      File "/usr/lib/python3.8/site-packages/compose/cli/main.py", line 1088, in up
        return self.project.up(
      File "/usr/lib/python3.8/site-packages/compose/project.py", line 565, in up
        results, errors = parallel.parallel_execute(
      File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
        raise error_to_reraise
      File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
        result = func(obj)
      File "/usr/lib/python3.8/site-packages/compose/project.py", line 548, in do
        return service.execute_convergence_plan(
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 567, in execute_convergence_plan
        return self._execute_convergence_start(
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 506, in _execute_convergence_start
        _, errors = parallel_execute(
      File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 112, in parallel_execute
        raise error_to_reraise
      File "/usr/lib/python3.8/site-packages/compose/parallel.py", line 210, in producer
        result = func(obj)
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 508, in <lambda>
        lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 620, in start_container_if_stopped
        return self.start_container(container)
      File "/usr/lib/python3.8/site-packages/compose/service.py", line 627, in start_container
        if "driver failed programming external connectivity" in ex.explanation:
    TypeError: a bytes-like object is required, not 'str'

</p>
</details>

/edit
yeap, on ubuntu its fine, what I also learned is that centos is no longer docker friendly

**Comment by DoTheEvo** [comment]
works now, I myself cant reproduce, sorry.
