### ISSUE TITLE
Crash in team view agent stats

### ISSUE THREAD

**Issue by azul** [helpyio/helpy#593]
<pre>
ActionView::Template::Error (undefined method `created_at' for nil:NilClass):
    54:   </div>
    55: 
    56:   <div class="agent-response-time agent-stat">
    57:     <% delays = @responded_topics.where(assigned_user: agent_stats.assigned_user).map { |t| t.posts.second.created_at - t.created_at } %>
    58:     <h4>
    59:       <% if delays.empty? %>
    60:         -
  app/views/admin/dashboard/_agent_stats.html.erb:57:in `block in _app_views_admin_dashboard__agent_stats_html_erb___3175801349380782580_69923543110080'
  app/views/admin/dashboard/_agent_stats.html.erb:57:in `_app_views_admin_dashboard__agent_stats_html_erb___3175801349380782580_69923543110080'
  app/views/admin/dashboard/stats.html.erb:92:in `block in _app_views_admin_dashboard_stats_html_erb___190842625663102872_69923543815960'
  app/views/admin/dashboard/stats.html.erb:74:in `_app_views_admin_dashboard_stats_html_erb___190842625663102872_69923543815960'
  app/controllers/application_controller.rb:206:in `set_time_zone'

</pre>

I assume some thread does not have a second post yet but still is assigned.

**Comment by azul** [comment]
Interestingly the topic that triggered this did not have an initial post by the user. It only had a title. It was submitted by email. Maybe the mail was empty or not processed correctly.

**Comment by scott** [comment]
Hey @azul thanks for sharing this!  We still see a rare issue with the email processor and that leads to a `Topic` being created that does not have a first `Post`.  I would love it if you could figure out any more details about what caused this.

**Comment by azul** [comment]
Hey @scott 

Here's the error from the logs when processing the incoming mail:

```
ActiveRecord::StatementInvalid (PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xf1 0x61 0x20 0x79
: INSERT INTO "posts" ("body", "raw_email", "user_id", "kind", "topic_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"):
  lib/email_processor.rb:73:in `process'
```
The text parameters to Griddler::EmailsController#create as */* contained this: `e\xF1a`
There is no mentioning of encoding there. But i assume it was a not utf8 encoded email. The mail was in spanish and the character was probably an ñ
