### ISSUE TITLE
Error: ActionController::InvalidAuthenticityToken on receiving inbound email

### ISSUE THREAD

**Issue by robguthrie** [helpyio/helpy#925]
Hello, thanks for the fantastic tool. We're considering using Helpy to manage support requests at Loomio.

A key requirement for us is to keep our user data under our control, and we love to support open source tools.

I see there is a little support for mailin as a griddler email processor, but I'm having trouble using it.

I've added a mailin container to my docker-compose.yml file, and configured it to post to helpy:8080/email_processor, I've also configured helpy to use mailin as the inbound email handler and upgraded griddler to the latest verison (1.5.0)

I'm getting the following exception:

```
helpy          | Error during failsafe response: ActionController::InvalidAuthenticityToken
helpy          |   /usr/local/bundle/gems/actionpack-4.2.10/lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request'
helpy          |   /usr/local/bundle/gems/actionpack-4.2.10/lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request'
helpy          |   /usr/local/bundle/gems/devise-3.5.6/lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
helpy          |   /usr/local/bundle/gems/actionpack-4.2.10/lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token'
and so on
```

I'm surprised that rails is checking for an authenticity token on the inbound email route.. Any ideas how to disable this?

Btw, We'd love to become a helpy sponsor.

**Comment by scott** [comment]
Hey @robguthrie-

I have not done a whole lot with Mailin myself so I cannot be too much of a resource there, although if you post up your compose.yml I would be happy to take a look.  FYI, I have seen that exception occur when in fact the problem was something entirely unrelated in Helpy.  I have not taken the time to  figure out why that happens, but just a word of warning that the exception may not be what is breaking  the integration.  Can you shoot me a note at scott at helpy.io regarding sponsorship?

**Comment by scott** [comment]
Also... there is an IMAP strategy which also handles incoming email by getting email from a known inbox. That not currently in master, but but it works well and also keeps you in complete control of your mail as well.

**Comment by robguthrie** [comment]
That sounds good, would be keen to try it.
